language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

sudo: false

addons:
  apt:
    sources:
    - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
    packages:
    - lua-event
    - lua-sec
    - mosquitto
    - prosody
    - zookeeperd

services:
  - mosquitto
  - prosody
  - redis-server
  - zookeeper

install:
  - pip install nose coverage coveralls
  - pip install pytest>=2.7.3 --upgrade
  - pip install https://github.com/tcalmant/jsonrpclib/archive/master.zip
  - pip install paho-mqtt kazoo redis zeroconf
  - prosodyctl register user1 localhost foobar
  - prosodyctl register user2 localhost foobar

script:
  - nosetests -v --with-coverage --cover-package=pelix tests

after_success:
  - coveralls
