language: python
python: 3.5
sudo: false

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35

addons:
  apt:
    sources:
    - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
    packages:
    - mosquitto

services:
  - mosquitto
  - redis-server

install:
  - pip install tox coverage coveralls
  - pip install pytest>=2.7.3 --upgrade

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
