language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

sudo: false

addons:
  apt:
    sources:
    - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
    packages:
    - mosquitto
    - zookeeperd

services:
  - mosquitto
  - redis-server
  - zookeeper

install:
  - pip install nose coverage coveralls
  - pip install pytest>=2.7.3 --upgrade
  - pip install https://github.com/tcalmant/jsonrpclib/archive/master.zip
  - pip install paho-mqtt kazoo redis zeroconf

script:
  - nosetests --with-coverage --cover-package=pelix tests

after_success:
  - coveralls
